//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class device
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public device()
        {
            this.users = new HashSet<user>();
        }
    
        public int DeviceID { get; set; }

        [Required(ErrorMessage = "Device Name field cannot be empty.")]
        [DisplayName("Device Name")]
        [RegularExpression("^([a-zA-Z0-9_ ]*$)", ErrorMessage = "Device name can contain only letters, digits and spaces.")]
        public string DName { get; set; }


        [Required(ErrorMessage = "Device Manufacturer field cannot be empty.")]
        [DisplayName("Manufacturer")]
        [RegularExpression("^([a-zA-Z0-9_ ]*$)", ErrorMessage = "Device Manufacturer can contain only letters, digits and spaces.")]

        public string DManufacturer { get; set; }

        [Required(ErrorMessage = "Device Type field cannot be empty.")]
        [DisplayName("Device Type")]
        [RegularExpression("^([a-zA-Z]*$)", ErrorMessage = "Device Type can contain only letters.")]
        public string DType { get; set; }


        [Required(ErrorMessage = "Device Operating System field cannot be empty.")]
        [DisplayName("Operating System")]
        [RegularExpression("^([a-zA-Z0-9_ ]*$)", ErrorMessage = "Device name can contain only letters, digits and spaces.")]
        public string DOS { get; set; }


        [Required(ErrorMessage = "Device Operating System Version field cannot be empty.")]
        [DisplayName("Operating System Version")]
        [RegularExpression("^([a-zA-Z0-9_ .]*$)", ErrorMessage = "Device Operating System Version can contain only letters, digits, spaces and dot character.")]
        public string DOSVersion { get; set; }


        [Required(ErrorMessage = "Device Processor field cannot be empty.")]
        [DisplayName("Processor")]
        [RegularExpression("^([a-zA-Z0-9_ ]*$)", ErrorMessage = "Device Processor can contain only letters, digits and spaces.")]
        public string DProcessor { get; set; }


        [Required(ErrorMessage = "Device RAM field cannot be empty.")]
        [DisplayName("RAM")]
        [RegularExpression("^([a-zA-Z0-9_ ]*$)", ErrorMessage = "Device RAM can contain only letters, digits and spaces.")]
        public string DRAM { get; set; }


        public Nullable<int> UserID { get; set; }
    
        public virtual user user { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> users { get; set; }
    }
}
