//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomLogin.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.devices = new HashSet<device>();
        }
    
        public int userID { get; set; }


        [DisplayName("User Name")]
        [Required(ErrorMessage = "Username field cannot be empty.")]
        [MinLength(5, ErrorMessage = "Username length must be greater than 4.")]
        [MaxLength(15, ErrorMessage = "Username length must be lower than 16.")]
        [RegularExpression("^([a-zA-Z0-9]+$)", ErrorMessage = "Username can contain only letters and digits.")]
        public string userName { get; set; }


        [DataType(DataType.Password)]
        [DisplayName("Password")]
        [PasswordPropertyText]
        [Required(ErrorMessage = "Password field cannot be empty.")]
        [RegularExpression("^(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9]).{8,16}", ErrorMessage = "Password length must be between 8 and 16 characters and must contain lowercase letter, uppercase letter and digit.")]
        public string password { get; set; }


        [DisplayName("Confirm Password")]
        [PasswordPropertyText]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Password field cannot be empty.")]
        [Compare("password")]
        public string confirmPassword { get; set; }


        [DisplayName("Email")]
        [Required(ErrorMessage = "Email field cannot be empty.")]
        [DataType(DataType.EmailAddress)]
        public string email { get; set; }



        public Nullable<bool> isAdmin { get; set; }



        public string Location { get; set; }



        public Nullable<int> DeviceID { get; set; }



    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<device> devices { get; set; }



        public virtual device device { get; set; }




        public string LoginErrorMessage { get; set; }
    }
}
